# Site settings
title: James Morgan
description: 'Software Engineer and firm believer in the holy trinity - Tea, Toast & Techno'
url: 'http://jamesdmorgan.github.io'
baseurl: '/'
google_analytics: 'UA-83357734-1'
disqus_shortname: 'jamesdmorgan'

author:
  name: 'James Morgan'
  email: jamesdmorgan@gmail.com
  twitter_username: jamesdmorgan
  lastfm_username: jamesdmorgan
  spotify_username: jamesdmorgan
  flickr_username: dislocatedimagery
  github_username:  jamesdmorgan
  linkedin_username:  jdm2378

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jekyll-gist']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
